---
- name: Install Operators on Kubernetes Cluster
  hosts: localhost
  collections:
   - community.kubernetes
  tasks:

  - name: Create a Subscription for Service Binding Operator
    k8s:
      state: present
      definition:
        apiVersion: operators.coreos.com/v1alpha1
        kind: Subscription
        metadata:
          name: my-service-binding-operator
          namespace: openshift-operators
        spec:
          channel: stable
          name: rh-service-binding-operator
          source: redhat-operators
          sourceNamespace: openshift-marketplace
  - name: Create a Subscription for EDB Postgresql Operator
    k8s:
      state: present
      definition:
        apiVersion: operators.coreos.com/v1alpha1
        kind: Subscription
        metadata:
          name: my-cloud-native-postgresql
          namespace: openshift-operators
        spec:
          channel: stable-v1.18
          name: cloud-native-postgresql
          source: certified-operators
          sourceNamespace: openshift-marketplace
