---
total_ipv4_address_count: 256
kube_version: 4.11.17_openshift  # command to list all supported k8s/openshift `ibmcloud ks versions`
node_flavor: bx2.4x16
workers: 3
nfs_image: ibm-ubuntu-20-04-2-minimal-amd64-1
vsi_image: odo-test-windows # Image ID: r010-1c3682a3-0013-496f-a663-9772f933d5be || this image is a private image and only available in Developer QE
vsi_profile: bx2-2x8
sshkey_id: r010-0f01beeb-9b45-4406-93bb-4a8604c8a3e0  # sshkey id ansible-ssh-key in developer qe group in VPC sshkey